export const presets = {
  default: {
    backgroundColor: "#fff5e1",
    borderColor: "#ff7f50",
    pointColor: "#008080",
    pointNumberColor: "#000",
    altPointColor: "#ffd700",
    playerCheckerColor: "#fff",
    playerCheckerBorderColor: "#000",
    opponentCheckerColor: "#000",
    opponentCheckerBorderColor: "#fff",
    doublingCubeColor: "#fff",
  },
  warm: {
    backgroundColor: "#deb887",
    borderColor: "#8b4513",
    pointColor: "#8d0000",
    pointNumberColor: "#ffffff",
    altPointColor: "#df5f5dc",
    playerCheckerColor: "#b22222",
    playerCheckerBorderColor: "#8b0000",
    opponentCheckerColor: "#fffafa",
    opponentCheckerBorderColor: "#696969",
    doublingCubeColor: "#fff",
  },
};
