export const presets = {
  default: {
    backgroundColor: "#e9e9e9",
    borderColor: "#555555",
    pointColor: "#666666",
    pointNumberColor: "#f8f8f8",
    altPointColor: "#999999",
    playerCheckerColor: "#ffffff",
    playerCheckerBorderColor: "#111111",
    opponentCheckerColor: "#111111",
    opponentCheckerBorderColor: "#ffffff",
    doublingCubeColor: "#ffffff",
  },
  felt: {
    backgroundColor: "#1b4332",
    borderColor: "#2d6a4f",
    pointColor: "#40916c",
    pointNumberColor: "#d8f3dc",
    altPointColor: "#0d2b1e",
    playerCheckerColor: "#fffde7",
    playerCheckerBorderColor: "#f9a825",
    opponentCheckerColor: "#b71c1c",
    opponentCheckerBorderColor: "#7f0000",
    doublingCubeColor: "#fffde7",
  },
  coral: {
    backgroundColor: "#fff5e1",
    borderColor: "#ff7f50",
    pointColor: "#008080",
    pointNumberColor: "#000",
    altPointColor: "#00d4d4",
    playerCheckerColor: "#fff",
    playerCheckerBorderColor: "#000",
    opponentCheckerColor: "#000",
    opponentCheckerBorderColor: "#fff",
    doublingCubeColor: "#fff",
  },
  forest: {
    backgroundColor: "#1a2e1a",
    borderColor: "#5c4a1e",
    pointColor: "#6b8f47",
    pointNumberColor: "#e8f5e0",
    altPointColor: "#2d4a1e",
    playerCheckerColor: "#e8f5e0",
    playerCheckerBorderColor: "#a8c97a",
    opponentCheckerColor: "#0f1a0f",
    opponentCheckerBorderColor: "#6b8f47",
    doublingCubeColor: "#e8f5e0",
  },
  rose: {
    backgroundColor: "#f9eff2",
    borderColor: "#c2485a",
    pointColor: "#c2485a",
    pointNumberColor: "#fff",
    altPointColor: "#e8b4bc",
    playerCheckerColor: "#fff",
    playerCheckerBorderColor: "#c2485a",
    opponentCheckerColor: "#6b1a2a",
    opponentCheckerBorderColor: "#f4c2cb",
    doublingCubeColor: "#fff",
  },
  arctic: {
    backgroundColor: "#e8f4fd",
    borderColor: "#4a9eca",
    pointColor: "#1d6fa4",
    pointNumberColor: "#fff",
    altPointColor: "#b3d9f0",
    playerCheckerColor: "#ffffff",
    playerCheckerBorderColor: "#1d6fa4",
    opponentCheckerColor: "#0d3a5c",
    opponentCheckerBorderColor: "#4a9eca",
    doublingCubeColor: "#fff",
  },
  sand: {
    backgroundColor: "#f0e0c0",
    borderColor: "#c07840",
    pointColor: "#a05020",
    pointNumberColor: "#fff",
    altPointColor: "#d8b888",
    playerCheckerColor: "#fff8f0",
    playerCheckerBorderColor: "#a05020",
    opponentCheckerColor: "#4a2800",
    opponentCheckerBorderColor: "#c07840",
    doublingCubeColor: "#fff8f0",
  },
};
